In [3]:
import requests
from bs4 import BeautifulSoup as BS
import pandas as pd
import time
import matplotlib.pyplot as plt

In [4]:
page = requests.get('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017')
soup = BS(page.content, 'html.parser')

In [53]:
idk=soup.select('tr[class^="oddrow"]')
idk1=soup.select('tr[class^="evenrow"]')

# links to scrape from

In [36]:
list_years = []
i = 2002
for num in range(0,1):
    list_years.append(str(i))
    i+=1

In [37]:
links = []
for thing in list_years:
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing)
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/41')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/81')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/121')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/161')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/201')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/241')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/281')
    links.append('http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/'+thing+'/count/321')

In [51]:
links

['http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/41',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/81',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/121',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/161',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/201',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/241',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/281',
 'http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/321']

# Scoring

In [63]:
#u made a function for this below
names = []
PTS = []
FG_perc = []
_3p_perc = []
FT_perc = []
for thing in idk:
    names.append(thing.select('td')[1].string)
    PTS.append(thing.select('td')[3].string)
    FG_perc.append(thing.select('td')[5].string)
    _3p_perc.append(thing.select('td')[7].string)
    FT_perc.append(thing.select('td')[9].string)

In [64]:
#u made a function for this below
names_e = []
PTS_e = []
FG_perc_e = []
_3p_perc_e = []
FT_perc_e = []
for thing in idk1:
    names_e.append(thing.select('td')[1].string)
    PTS_e.append(thing.select('td')[3].string)
    FG_perc_e.append(thing.select('td')[5].string)
    _3p_perc_e.append(thing.select('td')[7].string)
    FT_perc_e.append(thing.select('td')[9].string)

In [66]:
len(names_e)

20

In [68]:
len(names)

20

In [106]:
def get_score_info (links):
    names = []
    PTS = []
    FG_perc = []
    _3p_perc = []
    FT_perc = []
    for link in links:
        print(link)
        page = requests.get(link)
        soup = BS(page.content, 'html.parser')
        idk=soup.select('tr[class^="oddrow"]')
        idk2=soup.select('tr[class^="evenrow"]')
        i = 0
        for thing in idk:
            try:    
                names.append(thing.select('td')[1].string)
                names.append(idk2[i].select('td')[1].string)
                PTS.append(float(thing.select('td')[3].string))
                PTS.append(float(idk2[i].select('td')[3].string))
                FG_perc.append(float(thing.select('td')[5].string))
                FG_perc.append(float(idk2[i].select('td')[5].string))
                _3p_perc.append(float(thing.select('td')[7].string))
                _3p_perc.append(float(idk2[i].select('td')[7].string))
                FT_perc.append(float(thing.select('td')[9].string))
                FT_perc.append(float(idk2[i].select('td')[9].string))
                i+=1
            except:
                continue
                i+=1
    return names, PTS, FG_perc, _3p_perc, FT_perc

In [107]:
names, PTS, FG_perc, _3p_perc, FT_perc = get_score_info (links)

http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/41
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/81
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/121
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/161
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/201
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/241
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/281
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2002/count/321

In [108]:
names

['Kansas',
 'Duke',
 'Oregon',
 'TCU',
 'Maryland',
 'Arizona',
 'Wagner',
 'Wake Forest',
 'Gonzaga',
 'Pepperdine',
 'East Tennessee State',
 'Stanford',
 'Georgetown',
 'St. Bonaventure',
 'Gardner-Webb',
 'Florida',
 'Tulsa',
 'Memphis',
 'St. Francis (BKN)',
 'Virginia',
 'Alabama A&M',
 'Hampton',
 'Alcorn State',
 'Colorado',
 'Tennessee Tech',
 'Georgia Southern',
 'UT Rio Grande Valley',
 'Missouri',
 'Texas Tech',
 'Texas',
 'Quinnipiac',
 'Murray State',
 'Notre Dame',
 'Ball State',
 'North Texas',
 'Oklahoma',
 'Western Kentucky',
 'Grambling',
 'UNLV',
 'Valparaiso',
 'UT Martin',
 'UConn',
 'New Mexico State',
 'Western Carolina',
 'Marshall',
 'USC',
 'Northern Illinois',
 'Tennessee State',
 'UCF',
 'Georgia State',
 'Texas A&M-CC',
 'Brown',
 'Illinois',
 'Cincinnati',
 'Morehead State',
 "Saint Joseph's",
 'UTSA',
 'Louisville',
 'Kentucky',
 'South Florida',
 'Baylor',
 'VMI',
 'Georgia Tech',
 'Appalachian State',
 'Kent State',
 'Arizona State',
 'UT Arlington',
 'Alabama',
 'Georgia',
 'LIU Brooklyn',
 'Oral Roberts',
 'Mississippi Valley State',
 'Creighton',
 'Southern Illinois',
 'NC State',
 'Milwaukee',
 'Wyoming',
 'Yale',
 'Oakland',
 'San Diego',
 'Vermont',
 'Troy',
 'Sacred Heart',
 'Manhattan',
 'Clemson',
 'IUPUI',
 'Ohio',
 'Howard',
 'Weber State',
 'Bowling Green',
 'Arkansas',
 'Minnesota',
 'San Diego State',
 'Miami',
 'Sam Houston State',
 'Texas State',
 'Eastern Illinois',
 'Marist',
 'Little Rock',
 'Ohio State',
 'Mississippi State',
 'Florida Atlantic',
 'Boston College',
 'Niagara',
 'UIC',
 'UCLA',
 'New Mexico',
 'Southern',
 'Charlotte',
 'UMBC',
 'Syracuse',
 'Wright State',
 'Nevada',
 'Western Illinois',
 'Western Michigan',
 'Sacramento State',
 'Dayton',
 'Marquette',
 'Chattanooga',
 'Pennsylvania',
 'Jackson State',
 'Northwestern State',
 'Prairie View A&M',
 'West Virginia',
 'Eastern Kentucky',
 'Iowa',
 'The Citadel',
 'Fresno State',
 'Arkansas State',
 'Wichita State',
 'Drexel',
 'Portland State',
 'Stetson',
 'Louisiana Tech',
 'Colgate',
 'Xavier',
 'VCU',
 'Lafayette',
 'California',
 'Pittsburgh',
 'UNC Greensboro',
 'Houston',
 'Ole Miss',
 'SMU',
 'Loyola Chicago',
 'North Carolina',
 'Tulane',
 "Hawai'i",
 'Belmont',
 'Centenary',
 'Vanderbilt',
 'Oklahoma State',
 'Washington',
 'Montana',
 'Central Connecticut',
 'Portland',
 'Florida State',
 'Tennessee',
 'Fairfield',
 'Fairleigh Dickinson',
 'Providence',
 'Long Beach State',
 'San Francisco',
 'Purdue',
 'SE Missouri St',
 'Radford',
 'Iona',
 'UL Monroe',
 'Northeastern',
 'Jacksonville',
 'Villanova',
 'Davidson',
 'Northern Iowa',
 'Missouri State',
 'DePaul',
 'Fordham',
 'Campbell',
 'Rider',
 'Seton Hall',
 'McNeese',
 'Austin Peay',
 'Washington State',
 'UAB',
 "St. John's",
 'BYU',
 'Jacksonville State',
 'Indiana',
 'Butler',
 'Idaho State',
 'Lamar',
 'Pacific',
 'Temple',
 'James Madison',
 'Central Michigan',
 'George Mason',
 'Montana State',
 'UC Irvine',
 'UNC Asheville',
 'Eastern Washington',
 'Nebraska',
 'Michigan State',
 'Iowa State',
 'South Carolina State',
 'Siena',
 'Coastal Carolina',
 'Lipscomb',
 'Elon',
 'George Washington',
 'Akron',
 'Louisiana',
 'Charleston',
 'Navy',
 'Virginia Tech',
 'Texas Southern',
 'Cal Poly',
 'High Point',
 'Drake',
 'Robert Morris',
 'UTEP',
 'Furman',
 'New Hampshire',
 'Loyola Marymount',
 'Norfolk State',
 'Colorado State',
 'LSU',
 'Winthrop',
 'Kansas State',
 'Monmouth',
 'Bethune-Cookman',
 'CSU Northridge',
 'South Carolina',
 'Rutgers',
 'Utah',
 'Evansville',
 'Northern Arizona',
 'Boston University',
 'Michigan',
 'Buffalo',
 'Santa Clara',
 'Cleveland State',
 'North Carolina A&T',
 'Old Dominion',
 'Illinois State',
 'UNC Wilmington',
 'Toledo',
 'Middle Tennessee',
 'Wisconsin',
 'Utah State',
 'Wofford',
 'Army',
 'Delaware',
 'Florida A&M',
 'La Salle',
 'Eastern Michigan',
 'New Orleans',
 'Lehigh',
 'UC Santa Barbara',
 'Arkansas-Pine Bluff',
 'Mercer',
 'American',
 'Maryland-Eastern Shore',
 'Hofstra',
 'Rice',
 'Green Bay',
 'Detroit Mercy',
 'Auburn',
 'Canisius',
 'Alabama State',
 'Morgan State',
 "Saint Peter's",
 'Texas A&M',
 'Denver',
 'Delaware State',
 'Southern Utah',
 'Binghamton',
 'Youngstown St',
 'UC Riverside',
 'South Alabama',
 'East Carolina',
 'Oregon State',
 'UMass',
 'Harvard',
 'Duquesne',
 'Miami (OH)',
 'UMKC',
 'Maine',
 'Florida International',
 'Liberty',
 'Penn State',
 'Stephen F. Austin',
 'Holy Cross',
 'Saint Louis',
 'Chicago State',
 'St. Francis (PA)',
 'William & Mary',
 'Birmingham-Southern',
 'Dartmouth',
 'Charleston Southern',
 'Richmond',
 'Boise State',
 'CSU Fullerton',
 'Southern Miss',
 'San José St',
 'Rhode Island',
 'Indiana State',
 'Bucknell',
 "Saint Mary's",
 'Hartford',
 'Stony Brook',
 "Mt. St. Mary's",
 'Bradley',
 'Samford',
 'Princeton',
 'Northwestern',
 'Nicholls',
 'Loyola (MD)',
 'Towson',
 'Coppin State',
 'Morris Brown',
 'Cornell',
 'Air Force',
 'SE Louisiana',
 'Albany',
 'Idaho',
 'Columbia']

In [109]:
names.pop(-1)

'Columbia'

In [99]:
names

['Kansas',
 'Duke',
 'Oregon',
 'TCU',
 'Maryland',
 'Arizona',
 'Wagner',
 'Wake Forest',
 'Gonzaga',
 'Pepperdine',
 'East Tennessee State',
 'Stanford',
 'Georgetown',
 'St. Bonaventure',
 'Gardner-Webb',
 'Florida',
 'Tulsa',
 'Memphis',
 'St. Francis (BKN)',
 'Virginia',
 'Alabama A&M',
 'Hampton',
 'Alcorn State',
 'Colorado',
 'Tennessee Tech',
 'Georgia Southern',
 'UT Rio Grande Valley',
 'Missouri',
 'Texas Tech',
 'Texas',
 'Quinnipiac',
 'Murray State',
 'Notre Dame',
 'Ball State',
 'North Texas',
 'Oklahoma',
 'Western Kentucky',
 'Grambling',
 'UNLV',
 'Valparaiso',
 'UT Martin',
 'UConn',
 'New Mexico State',
 'Western Carolina',
 'Marshall',
 'USC',
 'Northern Illinois',
 'Tennessee State',
 'UCF',
 'Georgia State',
 'Texas A&M-CC',
 'Brown',
 'Illinois',
 'Cincinnati',
 'Morehead State',
 "Saint Joseph's",
 'UTSA',
 'Louisville',
 'Kentucky',
 'South Florida',
 'Baylor',
 'VMI',
 'Georgia Tech',
 'Appalachian State',
 'Kent State',
 'Arizona State',
 'UT Arlington',
 'Alabama',
 'Georgia',
 'LIU Brooklyn',
 'Oral Roberts',
 'Mississippi Valley State',
 'Creighton',
 'Southern Illinois',
 'NC State',
 'Milwaukee',
 'Wyoming',
 'Yale',
 'Oakland',
 'San Diego',
 'Vermont',
 'Troy',
 'Sacred Heart',
 'Manhattan',
 'Clemson',
 'IUPUI',
 'Ohio',
 'Howard',
 'Weber State',
 'Bowling Green',
 'Arkansas',
 'Minnesota',
 'San Diego State',
 'Miami',
 'Sam Houston State',
 'Texas State',
 'Eastern Illinois',
 'Marist',
 'Little Rock',
 'Ohio State',
 'Mississippi State',
 'Florida Atlantic',
 'Boston College',
 'Niagara',
 'UIC',
 'UCLA',
 'New Mexico',
 'Southern',
 'Charlotte',
 'UMBC',
 'Syracuse',
 'Wright State',
 'Nevada',
 'Western Illinois',
 'Western Michigan',
 'Sacramento State',
 'Dayton',
 'Marquette',
 'Chattanooga',
 'Pennsylvania',
 'Jackson State',
 'Northwestern State',
 'Prairie View A&M',
 'West Virginia',
 'Eastern Kentucky',
 'Iowa',
 'The Citadel',
 'Fresno State',
 'Arkansas State',
 'Wichita State',
 'Drexel',
 'Portland State',
 'Stetson',
 'Louisiana Tech',
 'Colgate',
 'Xavier',
 'VCU',
 'Lafayette',
 'California',
 'Pittsburgh',
 'UNC Greensboro',
 'Houston',
 'Ole Miss',
 'SMU',
 'Loyola Chicago',
 'North Carolina',
 'Tulane',
 "Hawai'i",
 'Belmont',
 'Centenary',
 'Vanderbilt',
 'Oklahoma State',
 'Washington',
 'Montana',
 'Central Connecticut',
 'Portland',
 'Florida State',
 'Tennessee',
 'Fairfield',
 'Fairleigh Dickinson',
 'Providence',
 'Long Beach State',
 'San Francisco',
 'Purdue',
 'SE Missouri St',
 'Radford',
 'Iona',
 'UL Monroe',
 'Northeastern',
 'Jacksonville',
 'Villanova',
 'Davidson',
 'Northern Iowa',
 'Missouri State',
 'DePaul',
 'Fordham',
 'Campbell',
 'Rider',
 'Seton Hall',
 'McNeese',
 'Austin Peay',
 'Washington State',
 'UAB',
 "St. John's",
 'BYU',
 'Jacksonville State',
 'Indiana',
 'Butler',
 'Idaho State',
 'Lamar',
 'Pacific',
 'Temple',
 'James Madison',
 'Central Michigan',
 'George Mason',
 'Montana State',
 'UC Irvine',
 'UNC Asheville',
 'Eastern Washington',
 'Nebraska',
 'Michigan State',
 'Iowa State',
 'South Carolina State',
 'Siena',
 'Coastal Carolina',
 'Lipscomb',
 'Elon',
 'George Washington',
 'Akron',
 'Louisiana',
 'Charleston',
 'Navy',
 'Virginia Tech',
 'Texas Southern',
 'Cal Poly',
 'High Point',
 'Drake',
 'Robert Morris',
 'UTEP',
 'Furman',
 'New Hampshire',
 'Loyola Marymount',
 'Norfolk State',
 'Colorado State',
 'LSU',
 'Winthrop',
 'Kansas State',
 'Monmouth',
 'Bethune-Cookman',
 'CSU Northridge',
 'South Carolina',
 'Rutgers',
 'Utah',
 'Evansville',
 'Northern Arizona',
 'Boston University',
 'Michigan',
 'Buffalo',
 'Santa Clara',
 'Cleveland State',
 'North Carolina A&T',
 'Old Dominion',
 'Illinois State',
 'UNC Wilmington',
 'Toledo',
 'Middle Tennessee',
 'Wisconsin',
 'Utah State',
 'Wofford',
 'Army',
 'Delaware',
 'Florida A&M',
 'La Salle',
 'Eastern Michigan',
 'New Orleans',
 'Lehigh',
 'UC Santa Barbara',
 'Arkansas-Pine Bluff',
 'Mercer',
 'American',
 'Maryland-Eastern Shore',
 'Hofstra',
 'Rice',
 'Green Bay',
 'Detroit Mercy',
 'Auburn',
 'Canisius',
 'Alabama State',
 'Morgan State',
 "Saint Peter's",
 'Texas A&M',
 'Denver',
 'Delaware State',
 'Southern Utah',
 'Binghamton',
 'Youngstown St',
 'UC Riverside',
 'South Alabama',
 'East Carolina',
 'Oregon State',
 'UMass',
 'Harvard',
 'Duquesne',
 'Miami (OH)',
 'UMKC',
 'Maine',
 'Florida International',
 'Liberty',
 'Penn State',
 'Stephen F. Austin',
 'Holy Cross',
 'Saint Louis',
 'Chicago State',
 'St. Francis (PA)',
 'William & Mary',
 'Birmingham-Southern',
 'Dartmouth',
 'Charleston Southern',
 'Richmond',
 'Boise State',
 'CSU Fullerton',
 'Southern Miss',
 'San José St',
 'Rhode Island',
 'Indiana State',
 'Bucknell',
 "Saint Mary's",
 'Hartford',
 'Stony Brook',
 "Mt. St. Mary's",
 'Bradley',
 'Samford',
 'Princeton',
 'Northwestern',
 'Nicholls',
 'Loyola (MD)',
 'Towson',
 'Coppin State',
 'Morris Brown',
 'Cornell',
 'Air Force',
 'SE Louisiana',
 'Albany',
 'Idaho']

In [110]:
D = {'name':names, 'PTS':PTS, 'FG_perc':FG_perc, '_3p_perc':_3p_perc, 'FT_perc':FT_perc}

In [111]:
df = pd.DataFrame(data=D)

In [114]:
df

                     name   PTS  FG_perc  _3p_perc  FT_perc
0                  Kansas  92.0    0.511     0.422    0.718
1                    Duke  89.7    0.498     0.359    0.689
2                  Oregon  85.9    0.489     0.424    0.775
3                     TCU  85.3    0.431     0.342    0.709
4                Maryland  85.3    0.483     0.370    0.710
5                 Arizona  83.0    0.462     0.380    0.730
6                  Wagner  82.0    0.468     0.369    0.707
7             Wake Forest  81.8    0.476     0.356    0.738
8                 Gonzaga  81.6    0.478     0.397    0.731
9              Pepperdine  81.5    0.456     0.367    0.715
10   East Tennessee State  81.5    0.459     0.317    0.704
11               Stanford  81.2    0.453     0.347    0.701
12             Georgetown  81.1    0.447     0.347    0.725
13        St. Bonaventure  81.0    0.432     0.355    0.763
14           Gardner-Webb  80.6    0.439     0.350    0.670
15                Florida  80.4    0.472     0.352    0.698
16                  Tulsa  80.4    0.477     0.406    0.751
17                Memphis  80.3    0.454     0.347    0.670
18      St. Francis (BKN)  80.2    0.468     0.350    0.673
19               Virginia  80.0    0.461     0.338    0.723
20            Alabama A&M  79.9    0.405     0.311    0.672
21                Hampton  79.9    0.486     0.352    0.669
22           Alcorn State  79.8    0.463     0.377    0.644
23               Colorado  79.7    0.453     0.355    0.673
24         Tennessee Tech  79.7    0.484     0.375    0.717
25       Georgia Southern  79.6    0.454     0.343    0.636
26   UT Rio Grande Valley  79.6    0.477     0.368    0.688
27               Missouri  79.5    0.458     0.391    0.693
28             Texas Tech  79.5    0.468     0.378    0.684
29                  Texas  79.0    0.453     0.370    0.682
..                    ...   ...      ...       ...      ...
294        William & Mary  63.0    0.389     0.320    0.641
295   Birmingham-Southern  62.9    0.418     0.329    0.654
296             Dartmouth  62.9    0.428     0.392    0.693
297   Charleston Southern  62.9    0.430     0.308    0.671
298              Richmond  62.8    0.400     0.314    0.698
299           Boise State  62.6    0.414     0.309    0.694
300         CSU Fullerton  62.6    0.400     0.318    0.657
301         Southern Miss  62.1    0.406     0.306    0.669
302           San José St  62.1    0.407     0.326    0.659
303          Rhode Island  61.8    0.381     0.310    0.688
304         Indiana State  61.8    0.415     0.349    0.637
305              Bucknell  61.8    0.428     0.344    0.622
306          Saint Mary's  61.0    0.399     0.275    0.677
307              Hartford  60.9    0.402     0.297    0.625
308           Stony Brook  60.9    0.411     0.329    0.708
309        Mt. St. Mary's  60.7    0.363     0.295    0.652
310               Bradley  60.7    0.389     0.311    0.716
311               Samford  60.5    0.478     0.366    0.702
312             Princeton  59.8    0.446     0.342    0.725
313          Northwestern  59.6    0.418     0.336    0.605
314              Nicholls  59.3    0.363     0.288    0.611
315           Loyola (MD)  58.9    0.371     0.270    0.654
316                Towson  58.4    0.426     0.287    0.620
317          Coppin State  58.2    0.378     0.271    0.712
318          Morris Brown  57.9    0.373     0.283    0.589
319               Cornell  57.7    0.379     0.312    0.693
320             Air Force  57.3    0.463     0.373    0.712
321          SE Louisiana  57.1    0.408     0.329    0.665
322                Albany  56.9    0.387     0.328    0.670
323                 Idaho  55.1    0.378     0.291    0.673

[324 rows x 5 columns]

In [115]:
df8=pd.read_csv('df8.csv')

In [117]:
len(list(df8['first_team']))

126

In [123]:
df8.head(5)

,Unnamed: 0,Unnamed: 0.1,first_team,second_team,winner,point_difference,result,name,team_rank,win
0,0,0,1,16,1,15,1,Maryland,1,1
1,1,1,1,16,1,15,1,Siena,16,0
2,2,2,8,9,8,1,1,Wisconsin,8,1
3,3,3,8,9,8,1,1,St. John's (NY),9,0
4,4,4,5,12,12,7,2,Marquette,5,0

In [119]:
df8.rename(columns = {'team_name':'name'}, inplace = True)

In [121]:
possibly=pd.merge(df8,df,how='inner',on='name')

In [128]:
import pandas as pd

In [130]:
pd.set_option('display.max_rows', 200)

In [131]:
possibly

,Unnamed: 0,Unnamed: 0.1,first_team,second_team,winner,point_difference,result,name,team_rank,win,PTS,FG_perc,_3p_perc,FT_perc
0,0,0,1,16,1,15,1,Maryland,1,1,85.3,0.483,0.370,0.710
1,16,16,1,8,1,7,1,Maryland,1,1,85.3,0.483,0.370,0.710
2,24,24,1,4,1,3,1,Maryland,1,1,85.3,0.483,0.370,0.710
3,28,28,1,2,1,1,1,Maryland,1,1,85.3,0.483,0.370,0.710
4,120,120,1,1,1,0,0,Maryland,1,9999,85.3,0.483,0.370,0.710
5,124,124,1,5,1,4,1,Maryland,1,1,85.3,0.483,0.370,0.710
6,1,1,1,16,1,15,1,Siena,16,0,69.6,0.415,0.347,0.742
7,2,2,8,9,8,1,1,Wisconsin,8,1,66.9,0.438,0.352,0.719
8,17,17,1,8,1,7,1,Wisconsin,8,0,66.9,0.438,0.352,0.719
9,4,4,5,12,12,7,2,Marquette,5,0,73.3,0.474,0.381,0.692
10,5,5,5,12,12,7,2,Tulsa,12,1,80.4,0.477,0.406,0.751
11,18,18,12,4,4,8,1,Tulsa,12,0,80.4,0.477,0.406,0.751
12,6,6,4,13,4,9,1,Kentucky,4,1,76.6,0.448,0.309,0.670
13,19,19,12,4,4,8,1,Kentucky,4,1,76.6,0.448,0.309,0.670
14,25,25,1,4,1,3,1,Kentucky,4,0,76.6,0.448,0.309,0.670
15,7,7,4,13,4,9,1,Valparaiso,13,0,78.0,0.451,0.350,0.665
16,8,8,6,11,11,5,2,Texas Tech,6,0,79.5,0.468,0.378,0.684
17,9,9,6,11,11,5,2,Southern Illinois,11,1,75.9,0.463,0.372,0.621
18,20,20,11,3,11,8,2,Southern Illinois,11,1,75.9,0.463,0.372,0.621
19,26,26,11,2,2,9,1,Southern Illinois,11,0,75.9,0.463,0.372,0.621
20,10,10,3,14,3,11,1,Georgia,3,1,76.1,0.447,0.315,0.734
21,21,21,11,3,11,8,2,Georgia,3,0,76.1,0.447,0.315,0.734
22,11,11,3,14,3,11,1,Murray State,14,0,78.9,0.452,0.319,0.727
23,12,12,7,10,7,3,1,NC State,7,1,75.7,0.454,0.359,0.750
24,22,22,7,2,2,5,1,NC State,7,0,75.7,0.454,0.359,0.750
25,13,13,7,10,7,3,1,Michigan State,10,0,69.7,0.467,0.398,0.764
26,14,14,2,15,2,13,1,UConn,2,1,77.9,0.481,0.385,0.691
27,23,23,7,2,2,5,1,UConn,2,1,77.9,0.481,0.385,0.691
28,27,27,11,2,2,9,1,UConn,2,1,77.9,0.481,0.385,0.691
29,29,29,1,2,1,1,1,UConn,2,0,77.9,0.481,0.385,0.691
30,15,15,2,15,2,13,1,Hampton,15,0,79.9,0.486,0.352,0.669
31,30,30,1,16,1,15,1,Kansas,1,1,92.0,0.511,0.422,0.718
32,46,46,1,8,1,7,1,Kansas,1,1,92.0,0.511,0.422,0.718
33,54,54,1,4,1,3,1,Kansas,1,1,92.0,0.511,0.422,0.718
34,58,58,1,2,1,1,1,Kansas,1,1,92.0,0.511,0.422,0.718
35,121,121,1,1,1,0,0,Kansas,1,9999,92.0,0.511,0.422,0.718
36,31,31,1,16,1,15,1,Holy Cross,16,0,63.3,0.409,0.340,0.693
37,32,32,8,9,8,1,1,Stanford,8,1,81.2,0.453,0.347,0.701
38,47,47,1,8,1,7,1,Stanford,8,0,81.2,0.453,0.347,0.701
39,33,33,8,9,8,1,1,Western Kentucky,9,0,78.2,0.469,0.380,0.705
40,34,34,5,12,12,7,2,Florida,5,0,80.4,0.472,0.352,0.698
41,35,35,5,12,12,7,2,Creighton,12,1,75.9,0.468,0.367,0.730
42,48,48,12,4,4,8,1,Creighton,12,0,75.9,0.468,0.367,0.730
43,36,36,4,13,4,9,1,Illinois,4,1,77.3,0.467,0.356,0.746
44,49,49,12,4,4,8,1,Illinois,4,1,77.3,0.467,0.356,0.746
45,55,55,1,4,1,3,1,Illinois,4,0,77.3,0.467,0.356,0.746
46,37,37,4,13,4,9,1,San Diego State,13,0,74.7,0.479,0.358,0.659
47,38,38,6,11,6,5,1,Texas,6,1,79.0,0.453,0.370,0.682
48,50,50,6,3,6,3,2,Texas,6,1,79.0,0.453,0.370,0.682
49,56,56,6,2,2,4,1,Texas,6,0,79.0,0.453,0.370,0.682
50,39,39,6,11,6,5,1,Boston College,11,0,74.1,0.421,0.339,0.695
51,40,40,3,14,3,11,1,Mississippi State,3,1,74.2,0.480,0.352,0.650
52,51,51,6,3,6,3,2,Mississippi State,3,0,74.2,0.480,0.352,0.650
53,42,42,7,10,7,3,1,Wake Forest,7,1,81.8,0.476,0.356,0.738
54,52,52,7,2,2,5,1,Wake Forest,7,0,81.8,0.476,0.356,0.738
55,43,43,7,10,7,3,1,Pepperdine,10,0,81.5,0.456,0.367,0.715
56,44,44,2,15,2,13,1,Oregon,2,1,85.9,0.489,0.424,0.775
57,53,53,7,2,2,5,1,Oregon,2,1,85.9,0.489,0.424,0.775
58,57,57,6,2,2,4,1,Oregon,2,1,85.9,0.489,0.424,0.775
59,59,59,1,2,1,1,1,Oregon,2,0,85.9,0.489,0.424,0.775
60,45,45,2,15,2,13,1,Montana,15,0,71.9,0.455,0.360,0.673
61,60,60,1,16,1,15,1,Duke,1,1,89.7,0.498,0.359,0.689
62,76,76,1,8,1,7,1,Duke,1,1,89.7,0.498,0.359,0.689
63,84,84,1,5,5,4,2,Duke,1,0,89.7,0.498,0.359,0.689
64,61,61,1,16,1,15,1,Winthrop,16,0,68.5,0.423,0.314,0.656
65,62,62,8,9,8,1,1,Notre Dame,8,1,78.8,0.460,0.379,0.702
66,77,77,1,8,1,7,1,Notre Dame,8,0,78.8,0.460,0.379,0.702
67,63,63,8,9,8,1,1,Charlotte,9,0,73.9,0.444,0.369,0.705
68,64,64,5,12,5,7,1,Indiana,5,1,70.2,0.452,0.394,0.709
69,78,78,5,13,5,8,1,Indiana,5,1,70.2,0.452,0.394,0.709
70,85,85,1,5,5,4,2,Indiana,5,1,70.2,0.452,0.394,0.709
71,88,88,5,10,5,5,1,Indiana,5,1,70.2,0.452,0.394,0.709
72,123,123,2,5,5,3,2,Indiana,5,1,70.2,0.452,0.394,0.709
73,125,125,1,5,1,4,1,Indiana,5,0,70.2,0.452,0.394,0.709
74,65,65,5,12,5,7,1,Utah,12,0,67.7,0.470,0.403,0.678
75,66,66,4,13,13,9,2,USC,4,0,77.6,0.441,0.345,0.696
76,67,67,4,13,13,9,2,UNC Wilmington,13,1,67.1,0.434,0.377,0.680
77,79,79,5,13,5,8,1,UNC Wilmington,13,0,67.1,0.434,0.377,0.680
78,68,68,6,11,6,5,1,California,6,1,72.6,0.454,0.317,0.675
79,80,80,6,3,3,3,1,California,6,0,72.6,0.454,0.317,0.675
80,71,71,3,14,3,11,1,Central Connecticut,14,0,71.8,0.458,0.346,0.735
81,72,72,7,10,10,3,2,Oklahoma State,7,0,72.0,0.450,0.330,0.639
82,73,73,7,10,10,3,2,Kent State,10,1,76.4,0.473,0.371,0.726
83,82,82,10,2,10,8,2,Kent State,10,1,76.4,0.473,0.371,0.726
84,87,87,3,10,10,7,2,Kent State,10,1,76.4,0.473,0.371,0.726
85,89,89,5,10,5,5,1,Kent State,10,0,76.4,0.473,0.371,0.726
86,74,74,2,15,2,13,1,Alabama,2,1,76.2,0.439,0.309,0.729
87,83,83,10,2,10,8,2,Alabama,2,0,76.2,0.439,0.309,0.729
88,75,75,2,15,2,13,1,Florida Atlantic,15,0,74.2,0.427,0.339,0.660
89,90,90,1,16,1,15,1,Cincinnati,1,1,77.2,0.466,0.359,0.707
90,106,106,1,8,8,7,2,Cincinnati,1,0,77.2,0.466,0.359,0.707
91,91,91,1,16,1,15,1,Boston University,16,0,67.6,0.429,0.365,0.684
92,92,92,8,9,8,1,1,UCLA,8,1,73.9,0.475,0.406,0.682
93,107,107,1,8,8,7,2,UCLA,8,1,73.9,0.475,0.406,0.682
94,114,114,8,12,12,4,2,UCLA,8,0,73.9,0.475,0.406,0.682
95,93,93,8,9,8,1,1,Ole Miss,9,0,72.5,0.465,0.386,0.738
96,95,95,5,12,12,7,2,Missouri,12,1,79.5,0.458,0.391,0.693
97,108,108,12,4,12,8,2,Missouri,12,1,79.5,0.458,0.391,0.693
98,115,115,8,12,12,4,2,Missouri,12,1,79.5,0.458,0.391,0.693
99,118,118,12,2,2,10,1,Missouri,12,0,79.5,0.458,0.391,0.693
100,96,96,4,13,4,9,1,Ohio State,4,1,74.2,0.490,0.386,0.674
101,109,109,12,4,12,8,2,Ohio State,4,0,74.2,0.490,0.386,0.674
102,97,97,4,13,4,9,1,Davidson,13,0,70.9,0.435,0.355,0.685
103,98,98,6,11,11,5,2,Gonzaga,6,0,81.6,0.478,0.397,0.731
104,99,99,6,11,11,5,2,Wyoming,11,1,75.6,0.456,0.301,0.698
105,110,110,11,3,3,8,1,Wyoming,11,0,75.6,0.456,0.301,0.698
106,100,100,3,14,3,11,1,Arizona,3,1,83.0,0.462,0.380,0.730
107,111,111,11,3,3,8,1,Arizona,3,1,83.0,0.462,0.380,0.730
108,116,116,3,2,2,1,1,Arizona,3,0,83.0,0.462,0.380,0.730
109,102,102,7,10,7,3,1,Xavier,7,1,72.7,0.451,0.358,0.718
110,112,112,7,2,2,5,1,Xavier,7,0,72.7,0.451,0.358,0.718
111,104,104,2,15,2,13,1,Oklahoma,2,1,78.2,0.447,0.359,0.760
112,113,113,7,2,2,5,1,Oklahoma,2,1,78.2,0.447,0.359,0.760
113,117,117,3,2,2,1,1,Oklahoma,2,1,78.2,0.447,0.359,0.760
114,119,119,12,2,2,10,1,Oklahoma,2,1,78.2,0.447,0.359,0.760
115,122,122,2,5,5,3,2,Oklahoma,2,0,78.2,0.447,0.359,0.760
116,105,105,2,15,2,13,1,UIC,15,0,73.9,0.445,0.412,0.653

In [105]:
list(df['PTS'])

['92.0',
 '89.7',
 '85.9',
 '85.3',
 '85.3',
 '83.0',
 '82.0',
 '81.8',
 '81.6',
 '81.5',
 '81.5',
 '81.2',
 '81.1',
 '81.0',
 '80.6',
 '80.4',
 '80.4',
 '80.3',
 '80.2',
 '80.0',
 '79.9',
 '79.9',
 '79.8',
 '79.7',
 '79.7',
 '79.6',
 '79.6',
 '79.5',
 '79.5',
 '79.0',
 '79.0',
 '78.9',
 '78.8',
 '78.5',
 '78.4',
 '78.2',
 '78.2',
 '78.1',
 '78.1',
 '78.0',
 '78.0',
 '77.9',
 '77.9',
 '77.9',
 '77.6',
 '77.6',
 '77.6',
 '77.6',
 '77.6',
 '77.5',
 '77.5',
 '77.4',
 '77.3',
 '77.2',
 '77.1',
 '77.0',
 '76.9',
 '76.8',
 '76.6',
 '76.6',
 '76.5',
 '76.5',
 '76.5',
 '76.4',
 '76.4',
 '76.4',
 '76.3',
 '76.2',
 '76.1',
 '76.1',
 '76.1',
 '76.1',
 '75.9',
 '75.9',
 '75.7',
 '75.6',
 '75.6',
 '75.5',
 '75.5',
 '75.5',
 '75.4',
 '75.3',
 '75.3',
 '75.3',
 '75.2',
 '75.2',
 '75.1',
 '74.9',
 '74.9',
 '74.8',
 '74.8',
 '74.8',
 '74.7',
 '74.7',
 '74.6',
 '74.6',
 '74.4',
 '74.3',
 '74.2',
 '74.2',
 '74.2',
 '74.2',
 '74.1',
 '74.0',
 '73.9',
 '73.9',
 '73.9',
 '73.9',
 '73.9',
 '73.8',
 '73.7',
 '73.7',
 '73.7',
 '73.6',
 '73.5',
 '73.4',
 '73.3',
 '73.3',
 '73.2',
 '73.1',
 '73.1',
 '73.1',
 '73.1',
 '73.0',
 '73.0',
 '72.9',
 '72.9',
 '72.9',
 '72.9',
 '72.9',
 '72.9',
 '72.9',
 '72.8',
 '72.8',
 '72.8',
 '72.7',
 '72.7',
 '72.6',
 '72.6',
 '72.6',
 '72.5',
 '72.5',
 '72.5',
 '72.4',
 '72.3',
 '72.2',
 '72.2',
 '72.2',
 '72.1',
 '72.1',
 '72.1',
 '72.0',
 '72.0',
 '71.9',
 '71.8',
 '71.8',
 '71.8',
 '71.7',
 '71.7',
 '71.5',
 '71.4',
 '71.2',
 '71.1',
 '71.1',
 '71.1',
 '71.1',
 '71.1',
 '71.1',
 '71.0',
 '71.0',
 '71.0',
 '70.9',
 '70.9',
 '70.8',
 '70.8',
 '70.7',
 '70.7',
 '70.7',
 '70.5',
 '70.5',
 '70.5',
 '70.4',
 '70.3',
 '70.3',
 '70.3',
 '70.2',
 '70.2',
 '70.2',
 '70.1',
 '70.1',
 '70.1',
 '70.0',
 '70.0',
 '70.0',
 '70.0',
 '69.9',
 '69.8',
 '69.8',
 '69.8',
 '69.8',
 '69.7',
 '69.7',
 '69.7',
 '69.6',
 '69.5',
 '69.5',
 '69.5',
 '69.5',
 '69.5',
 '69.4',
 '69.4',
 '69.4',
 '69.4',
 '69.4',
 '69.3',
 '69.2',
 '69.2',
 '69.2',
 '69.2',
 '69.1',
 '69.1',
 '69.0',
 '68.9',
 '68.8',
 '68.6',
 '68.5',
 '68.4',
 '68.4',
 '68.4',
 '68.3',
 '67.8',
 '67.7',
 '67.7',
 '67.6',
 '67.6',
 '67.6',
 '67.3',
 '67.3',
 '67.3',
 '67.2',
 '67.2',
 '67.1',
 '67.1',
 '67.1',
 '66.9',
 '66.9',
 '66.9',
 '66.9',
 '66.9',
 '66.8',
 '66.7',
 '66.5',
 '66.5',
 '66.5',
 '66.2',
 '66.2',
 '66.2',
 '66.1',
 '65.9',
 '65.9',
 '65.9',
 '65.8',
 '65.8',
 '65.7',
 '65.6',
 '65.5',
 '65.5',
 '65.5',
 '65.4',
 '65.1',
 '65.0',
 '65.0',
 '64.8',
 '64.7',
 '64.7',
 '64.6',
 '64.5',
 '64.5',
 '64.4',
 '64.3',
 '64.3',
 '64.1',
 '64.0',
 '63.9',
 '63.9',
 '63.6',
 '63.6',
 '63.6',
 '63.5',
 '63.4',
 '63.3',
 '63.1',
 '63.1',
 '63.0',
 '63.0',
 '62.9',
 '62.9',
 '62.9',
 '62.8',
 '62.6',
 '62.6',
 '62.1',
 '62.1',
 '61.8',
 '61.8',
 '61.8',
 '61.0',
 '60.9',
 '60.9',
 '60.7',
 '60.7',
 '60.5',
 '59.8',
 '59.6',
 '59.3',
 '58.9',
 '58.4',
 '58.2',
 '57.9',
 '57.7',
 '57.3',
 '57.1',
 '56.9',
 '55.1']

In [113]:
len(PTS)

324

In [62]:
idk1[0].select('td')[1].string

'The Citadel'

In [26]:
names

['UCLA',
 'Central Michigan',
 'Kentucky',
 'Marshall',
 'Portland State',
 'Lipscomb',
 'Gonzaga',
 'Kansas',
 'Marquette',
 'Creighton',
 'West Virginia',
 'William & Mary',
 'UMBC',
 'Iowa State',
 'North Dakota',
 'Auburn',
 'Indiana',
 'Green Bay',
 'Nevada',
 'Iowa']

In [15]:
#PTS
idk[0].select('td')[3].string

'90.4'

In [16]:
#FG%
idk[0].select('td')[5].string

'.519'

In [17]:
#3P%
idk[0].select('td')[7].string

'.405'

In [18]:
#FT%
idk[0].select('td')[9].string

'.745'

In [23]:
idk[0].select('td')[1].string

'UCLA'

In [ ]:
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/41
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/81
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/121
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/161
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/201
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/241
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/281
http://www.espn.com/mens-college-basketball/statistics/team/_/stat/scoring-per-game/sort/avgPoints/year/2017/count/321